gems: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 10
plugins: [jekyll-paginate]
exclude:
  [
    "node_modules",
    ".gitignore",
    "README.md",
    "gulpfile.js",
    "bigandy.github.sublime-project",
    "package.json",
    "jquery.js",
    "js/demos",
    "js/libs/**/*.html",
  ]
sass:
  style: :compressed
